#!/usr/bin/env node
/* Writes web/shared/ds/tokens.css from web/shared/ds/tokens.json (the owner's S2U Briefing tokens, vendored) and VERSION.
   tokens.test.ts regenerates in memory and refuses a tokens.css that differs, so edit tokens.json (or the
   artifact it came from) and run `npm run tokens -w shared`; never edit tokens.css. Spec section 4. */
import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, resolve } from 'path';

const here = dirname(fileURLToPath(import.meta.url));
const dir = resolve(here, '../ds');

/* Inserts '<first family> Fallback' right after the stack's first family, so the metric-matched local face
   (spec 4.2/5, web/shared/ds/fonts.css) is tried before the stack falls through to its named system fonts.
   e.g. "Oswald", "Arial Narrow", sans-serif -> "Oswald", 'Oswald Fallback', "Arial Narrow", sans-serif */
export function withFallback(stack) {
  const i = stack.indexOf(',');
  if (i === -1) return stack;
  const first = stack.slice(0, i).trim();
  const rest = stack.slice(i + 1).trim();
  const name = first.replace(/^["']|["']$/g, '');
  return `${first}, '${name} Fallback', ${rest}`;
}

export function generate(json, version) {
  const out = [];
  out.push('@layer s2u.tokens, s2u.base, s2u.components;');
  out.push(`/* GENERATED by tools/gen-tokens.mjs from tokens.json (${json.name}, v${json.version}) -- do not edit. */`);
  out.push('@layer s2u.tokens {');
  out.push('  :root {');
  out.push(`    --s2u-version: "${version}";`);
  const themeId = json.color.themes[0].id;
  out.push(`    /* colour, theme "${themeId}" */`);
  for (const t of json.color.tokens) {
    const v = typeof t.value === 'string' ? t.value : t.value[themeId];
    out.push(`    --s2u-${t.name}: ${v};`);
  }
  out.push('    /* type families */');
  for (const [k, v] of Object.entries(json.type.families)) out.push(`    --s2u-font-${k}: ${withFallback(v)};`);
  out.push('    /* type styles: font shorthand, tracking, italic */');
  for (const g of json.type.groups) {
    for (const s of g.styles) {
      out.push(`    --s2u-type-${s.name}: ${s.fontWeight} ${s.fontSize}/${s.lineHeight} var(--s2u-font-${g.family});`);
      out.push(`    --s2u-tracking-${s.name}: ${s.letterSpacing ?? '0'};`);
      out.push(`    --s2u-italic-${s.name}: ${s.fontStyle === 'italic' ? 'italic' : 'normal'};`);
    }
  }
  for (const fam of ['spacing', 'radius', 'shadow', 'opacity']) {
    if (!json[fam]) continue;
    out.push(`    /* ${fam} */`);
    for (const t of json[fam].tokens) out.push(`    --s2u-${t.name}: ${t.value};`);
  }
  out.push('  }');
  out.push('}');
  return out.join('\n') + '\n';
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const json = JSON.parse(readFileSync(resolve(dir, 'tokens.json'), 'utf-8'));
  const version = readFileSync(resolve(dir, 'VERSION'), 'utf-8').trim();
  writeFileSync(resolve(dir, 'tokens.css'), generate(json, version));
  console.log('wrote', resolve(dir, 'tokens.css'));
}
