"""Documentation maintenance: the registry in docs/DOC_MAINTENANCE.md, held to the tree.

Why this exists: on 2026-09-22 an audit of `docs/ROADMAP.md` found it two sprints and two wrong
instructions past its usefulness, and the same pass found `docs/HANDOFF.md` offering the next free
ruling number as R179 while R241 was in use -- a collision that had already happened once. The
difference between the documents that stayed true and the ones that rotted was not care; it was
whether anything could fail. This module is the thing that fails.

It is deliberately small. Eleven checks, each one aimed at a rot mechanism that actually bit this
project. The sixth was added on 2026-09-23 for the opposite reason -- a rot mechanism that had not
bitten yet only because nobody dared move anything: the Sprint 1-6 specs and plans were cited by
path from a hundred places, and `docs/archive/README.md` recorded them as "not moved, on purpose".
The seventh and eighth are R268's (2026-09-25): a byte ceiling on each document that grows by
appending, and "merged to main as vX" held to origin's tags.
The ninth and tenth are Sprint 13 Task R3's (2026-09-25): a ruling number defined twice, and a
cited ruling number with no definition, each found by the audit of that day and by nothing before it.

Nothing here fails on a calendar: a test that reddens because a week passed gets disabled,
and then the check is worse than nothing. Cadence is the sprint-close review in
`docs/DOC_MAINTENANCE.md`; this module only enforces what is mechanically true at any moment.
"""
import os
import re
import subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REGISTRY = "docs/DOC_MAINTENANCE.md"   # repo-relative, so tests can point ROOT at a planted tree

CLASSES = {
    "L": "Live -- must be true right now",
    "G": "Generated -- a tool writes it, a test holds it to its source",
    "N": "Narrative -- history and pointers, no live state",
    "S": "Snapshot -- frozen at its date, never updated",
    "C": "Contract -- rules that change only by decision",
    "A": "Archive -- superseded, kept because things cite it",
}

# What the registry must account for, one row each. Everything outside these globs is classified by
# location instead (docs/research/**, docs/superpowers/**, docs/audits/** are S; third_party/** and
# server/horizon-server/** are vendored; fixture READMEs belong to their fixtures). The rule is in
# docs/DOC_MAINTENANCE.md section 2.
COVERED = (
    ("", ("README.md", "CONTRIBUTING.md", "SECURITY.md", "THIRD_PARTY_NOTICES.md", "CLAUDE.md")),
    ("docs", None),
    ("docs/parity", None),
    ("docs/story", None),
    ("docs/archive", None),
)

# Suite counts. docs/DEVELOPING.md owns the *current* ones and may state them bare; everywhere else a
# count must be a DATED fact -- a date on the same line -- because that is the difference between a
# record ("764/764 on 2026-09-21", true forever) and a baseline ("baselines: C++ 686/686", which rots.
# It had rotted in four places by 2026-09-22). This is the mechanical half of section 6's rule: if a
# claim cannot be checked, do not make it; a dated one can always be checked.
COUNT_OWNER = "docs/DEVELOPING.md"
COUNT_PATTERNS = (
    re.compile(r"Total Tests:\s*\d+"),
    re.compile(r"\bRan\s+\d{3,}\s+tests\b"),
    re.compile(r"\b(?:C\+\+|ps2x_tests)\s+\d{3,}\s*/\s*\d{3,}\b"),
)

# The counter has ONE home, HANDOFF section 2's "Next free ruling number" line, since Sprint 14 D2 (R273).
# Until then CURRENT_SPRINT's header carried a second `next ruling:` line kept in step by hand -- on
# 2026-09-22 the two said R242 and R241 while R240 was the highest in use. The index of which rulings
# exist and where each is written is docs/RULINGS.md, generated by tools_py.rulings. The `next ruling`
# form stays in the pattern so the archived sprint files' old counter lines are still skipped as counters
# rather than read as rulings in use; test_exactly_one_counter_line refuses it in a live document.
RULING_LINE = re.compile(r"(?:Next free ruling number|next ruling)\s*:\s*\*{0,2}R(\d+)\*{0,2}", re.I)

# Check 6. A backticked path is a claim about the tree, and a move falsifies every one of them in
# silence -- which is why the Sprint 1-6 specs and plans sat under docs/superpowers/ for a sprint
# after they were dead: nobody could move them without breaking citations nothing would catch. The
# scan is deliberately narrow: backticks only (a prose mention is not a path), docs/ only (the rest
# of the tree moves under the compiler's nose, not the reader's), and a glob or a <placeholder>
# describes a set rather than a file. A path that does not exist *yet* is legitimate in a plan; mark
# that line with FUTURE_MARK and say so, so the exception is visible in the document itself.
BACKTICKED = re.compile(r"`([^`\n]+)`")
LOCATOR = re.compile(r":\d[\d,\-]*$")          # `docs/KNOWN.md:101`, `...md:318,355,433-435`
FUTURE_MARK = "<!-- docmaint: future -->"
COUNTER_DOCS = ("docs/HANDOFF.md",)
RULING_ANY = re.compile(r"\bR(\d{2,3})\b")
DATE = re.compile(r"\b20\d{2}-\d{2}-\d{2}\b")
ROW = re.compile(r"^\|\s*`([^`]+)`\s*\|\s*\*{0,2}([LGNSCA])\*{0,2}\s*\|")

# R268 (2026-09-25): the four documents that grow by appending get a byte ceiling each. The project
# audit of that day found CURRENT_SPRINT at 190 KB with about 12 % of it live, HANDOFF section 2 holding
# twelve pick-up points (three of them "now"), and STATUS's "Current state" block at 30 KB of dated
# bullets under a heading that says "keep it short". Nothing retired a block, so every close review read
# the newest one and never the stack under it. A ceiling makes skipping the archive step a failure.
# (path, heading prefix of the measured "## " block or None for the whole file, bytes). Set at the
# Sprint 13 Task R1 split from the content left live, with about 25 % headroom; HUMAN_TASKS was cut by
# Task R4 the same day (702 lines to one table, the old file archived) and its number lowered to
# match. Bytes are counted with LF line ends, so a Windows checkout (CRLF) and CI measure the same
# document the same way. When one fires, archive the
# oldest blocks (docs/archive/, a banner, a registry row) -- do not raise the number.
CEILINGS = (
    ("docs/CURRENT_SPRINT.md", None, 72000),       # 57,829 after the R1 split
    ("docs/HANDOFF.md", "## 2.", 3800),           # 3,022
    ("docs/HANDOFF.md", None, 6000),              # Sprint 14 I3: the whole file, transient (was 36,232)
    ("docs/STATUS.md", "## Current state", 2900),  # 2,309
    ("docs/HUMAN_TASKS.md", None, 12230),         # 9,786 after the R4 cut (was 104,000 over 82,968)
)

# R268 too: "merged to `main` as `vX.Y.Z`" is a claim about origin. On 2026-09-25 four live documents
# said it of v0.11.0 before the tag or the merge existed, so nobody was prompted to do either. A
# struck-through claim (~~...~~) is a retraction and is skipped, as check 6 skips a struck path.
MERGED_AS = re.compile(r"merged to `?main`? as `?(v\d+\.\d+\.\d+)`?", re.I)   # "Merged to MAIN as" too
STRUCK = re.compile(r"~~.*?~~")

# Checks 9 and 10 (Sprint 13 Task R3, 2026-09-25): one number, one ruling; a cited number has a text. The
# counter (check 2) only proves the NEXT number is free; it never noticed that R107, R109 and R110 had each
# been issued by two Sprint 8 plans for unrelated decisions, or that R114, R116 and R124 were cited for a
# week with no findable text (documents audit D55-D56). Both need a definition told apart from a citation.
# A definition is a line in a place a ruling is MADE (HANDOFF section 4 rule 9: a plan's rulings, or
# CURRENT_SPRINT when there is no plan, and what docs/archive/ keeps of both) in one of the house shapes:
#   - **R107** (Task 1): ...      **R181 -- ...**      - **R169 <em dash> ...**      1. **R237, REWRITTEN ...
#   - **R265**, **R266** (...)    ... **R173:** ...    **Ruling R115: ...**          **R264** (date, who): ...
# and NOT "R107's", "(R107)", "see **R107**", "**R238 was wrong**", "chosen by **R143**: ...", a bold range
# "**R241-R245**", a quoted line ("> ..."; a rewritten ruling quotes its first telling) or a code fence.
# A ledger row ("| R181 | ... | where it is written | status |") indexes a definition rather than repeating
# it: it counts as a definition for check 10 (R209 and R229 have only their rows) and is held to one row per
# number among ledger rows, but a row beside its plan's bullet is not a duplicate.
# A second issue is RECORDED, not renumbered: its definition line carries "cited as R<n>b" and is counted
# as R<n>b, and the citations that mean it say R<n>b. A number named but never issued carries a vacancy
# note, "R<n> -- vacant: <reason>", in the plan or ledger that owns its range.
# A range is never a definition, spaced or not ("**R241-R245**", "- **R107 - R110** (the close)").
RULING_DEF_LEAD = re.compile(
    r"^\s*(?:[-*+]\s+|\d+\.\s+)?\*\*R(\d{2,3})(?!\s*(?:—|–|--?)\s*R\d)(?=\*\*|\s*[(:,.]|\s+(?:—|–|--?)\s)")
RULING_DEF_MORE = re.compile(r"\*\*,\s*(?:and\s+)?\*\*R(\d{2,3})(?=\*\*)")
RULING_DEF_LABEL = re.compile(r"\*\*(?:Ruling\s+)?R(\d{2,3})(?::|\*\*\s+\([^)\n]*\):)")
RULING_LEDGER_ROW = re.compile(r"^\s*\|\s*\*{0,2}R(\d{2,3})\*{0,2}\s*\|")
RULING_SECOND = re.compile(r"cited as R(\d{2,3})b\b")
RULING_VACANT = re.compile(r"\bR(\d{2,3})\s*(?:—|–|--?)\s*vacant\s*:", re.I)
# A citation: the global number, or a recorded second issue (R107b). Sprint 12 numbered its own rulings
# S12-R<n> in their own namespace (R264), so "S12-R13" is not R13.
RULING_CITE = re.compile(r"(?<!S\d-)(?<!S\d\d-)\bR(\d{2,3})(b?)\b")


def _read(relpath):
    with open(os.path.join(ROOT, relpath), "r", encoding="utf-8", errors="replace") as fh:
        return fh.read()


def registry():
    """[{path, cls}] parsed from the registry table. Rows are `path` | CLASS | ..."""
    rows = []
    for line in _read(REGISTRY).split("\n"):
        m = ROW.match(line.strip())
        if m:
            rows.append({"path": m.group(1), "cls": m.group(2)})
    return rows


def covered_files():
    """Every markdown file the registry must account for, as repo-relative posix paths."""
    found = []
    for folder, explicit in COVERED:
        base = os.path.join(ROOT, folder) if folder else ROOT
        if explicit is not None:
            for name in explicit:
                if os.path.isfile(os.path.join(base, name)):
                    found.append(("%s/%s" % (folder, name)).lstrip("/"))
            continue
        if not os.path.isdir(base):
            continue
        for name in sorted(os.listdir(base)):
            if name.lower().endswith(".md") and os.path.isfile(os.path.join(base, name)):
                found.append("%s/%s" % (folder, name))
    return sorted(set(found))


def by_class(cls):
    return [r["path"] for r in registry() if r["cls"] == cls]


def head(relpath, lines=15):
    return "\n".join(_read(relpath).split("\n")[:lines])


def ruling_sources():
    """Every document max_ruling() reads, as repo-relative posix paths."""
    # Rulings are numbered where they are made: the live documents AND the plans' own "## Rulings"
    # sections (house convention since Sprint 5). A plan-only ruling not scanned here made the
    # counter read one too high on 2026-09-22, the first night the check ran.
    # The whole of docs/archive/ is read, top level and every subdirectory, because a ruling does not
    # stop existing when its block is archived: the Sprint 1-6 plans moved on 2026-09-23, and on
    # 2026-09-25 (Task R1) the Sprint 9-11 record and the Sprint 7-10 plans followed. Until then only
    # docs/archive/sprints-1-6/ was listed, so a close that archived the newest ledger would have let
    # the counter walk backwards -- the exact failure this check was written for.
    out = list(by_class("L")) + ["docs/STATUS.md"]
    d = os.path.join(ROOT, "docs", "superpowers", "plans")
    if os.path.isdir(d):
        out += ["docs/superpowers/plans/" + n for n in sorted(os.listdir(d)) if n.endswith(".md")]
    out += [p for p in linked_docs() if p.startswith("docs/archive/")]
    seen, uniq = set(), []
    for p in out:
        if p not in seen:
            seen.add(p)
            uniq.append(p)
    return uniq


def max_ruling():
    """The highest R<n> in use across the live documents, and where it was found."""
    best, where = 0, None
    for path in ruling_sources():
        if not os.path.isfile(os.path.join(ROOT, path)):
            continue
        for line in _read(path).split("\n"):
            # The counter line itself names the number that is NOT yet in use.
            if RULING_LINE.search(line):
                continue
            for m in RULING_ANY.finditer(line):
                n = int(m.group(1))
                if n > best:
                    best, where = n, path
    return best, where


def _ruling_key(name):
    """'R107b' -> (107, 'b'), so a report lists R107 before R107b before R108."""
    m = re.match(r"R(\d+)(b?)$", name)
    return (int(m.group(1)), m.group(2))


def ruling_definition_sources():
    """The documents a ruling may be MADE in (HANDOFF section 4 rule 9), as repo-relative posix paths."""
    # Under docs/archive/ only what WAS a plan or the sprint file is a home: the archived sprint-file records
    # (CURRENT_SPRINT-*.md) and the archived plans and specs (sprints-*/). An archived HANDOFF, HUMAN_TASKS or
    # STATUS restates rulings in the house shape and is not where they were made (2026-09-25: the archived
    # HUMAN_TASKS restated R246 and R247 and read as a second definition of each).
    def is_home(p):
        if p.startswith("docs/superpowers/plans/"):
            return True
        if p.startswith("docs/archive/"):
            rest = p[len("docs/archive/"):]
            return rest.startswith("sprints-") or rest.startswith("CURRENT_SPRINT")
        return False
    out = [p for p in ruling_sources() if is_home(p)]
    return ["docs/CURRENT_SPRINT.md"] + out   # the rule names it, whatever its registry row says


def ruling_records():
    """(definitions, ledger rows, vacancy notes), each {name: [(path, line), ...]}; see RULING_DEF_LEAD."""
    defs, rows, vacant = {}, {}, {}
    for path in ruling_definition_sources():
        if not os.path.isfile(os.path.join(ROOT, path)):
            continue
        fenced = False
        for i, line in enumerate(_read(path).split("\n"), 1):
            if line.lstrip().startswith("```"):
                fenced = not fenced
                continue
            if fenced or line.lstrip().startswith(">"):
                continue
            for m in RULING_VACANT.finditer(line):
                vacant.setdefault("R" + m.group(1), []).append((path, i))
            m = RULING_LEDGER_ROW.match(line)
            if m:
                rows.setdefault("R" + m.group(1), []).append((path, i))
                continue
            found = []
            m = RULING_DEF_LEAD.match(line)
            if m:
                found.append(m.group(1))
                pos = m.end()
                while True:
                    more = RULING_DEF_MORE.match(line, pos)
                    if not more:
                        break
                    found.append(more.group(1))
                    pos = more.end()
            for m in RULING_DEF_LABEL.finditer(line):
                if m.group(1) not in found:
                    found.append(m.group(1))
            seconds = set(RULING_SECOND.findall(line))
            for n in found:
                name = "R%s%s" % (n, "b" if n in seconds else "")
                defs.setdefault(name, []).append((path, i))
    return defs, rows, vacant


def duplicate_rulings():
    """[(name, [(path, line), ...])] for every ruling number defined more than once (check 9)."""
    defs, rows, _ = ruling_records()
    out = [(name, locs) for name, locs in defs.items() if len(locs) > 1]
    out += [(name, locs) for name, locs in rows.items() if len(locs) > 1]
    return sorted(out, key=lambda item: _ruling_key(item[0]))


def ruling_citations():
    """{name: [(path, line), ...]}: every R<n> and R<n>b named across the ruling scan (check 2's sources)."""
    cites = {}
    for path in ruling_sources():
        if not os.path.isfile(os.path.join(ROOT, path)):
            continue
        for i, line in enumerate(_read(path).split("\n"), 1):
            if RULING_LINE.search(line):
                continue   # the counter names the number NOT yet in use
            for m in RULING_CITE.finditer(line):
                locs = cites.setdefault("R%s%s" % (m.group(1), m.group(2)), [])
                if (path, i) not in locs:   # a line naming a number twice is one location
                    locs.append((path, i))
    return cites


def undefined_rulings():
    """[(name, [(path, line), ...])]: cited, at or under the highest number in use, and with no definition,
    no ledger row and no vacancy note anywhere (check 10). The locations are the citations."""
    defs, rows, vacant = ruling_records()
    hi = max_ruling()[0]
    out = []
    for name, locs in ruling_citations().items():
        n, _ = _ruling_key(name)
        if n > hi or name in defs or name in rows or name in vacant:
            continue
        out.append((name, locs))
    return sorted(out, key=lambda item: _ruling_key(item[0]))


def ruling_counters():
    """{path: number} for every document that offers a next-free ruling number."""
    out = {}
    for path in COUNTER_DOCS:
        if not os.path.isfile(os.path.join(ROOT, path)):
            continue
        m = RULING_LINE.search(_read(path))
        if m:
            out[path] = int(m.group(1))
    return out


def next_free_ruling():
    """The number docs/HANDOFF.md offers, or None when the line is missing."""
    return ruling_counters().get("docs/HANDOFF.md")


def count_offenders():
    """Registered documents stating a suite count with no date on the line to pin it to."""
    bad = []
    for row in registry():
        path = row["path"]
        if path == COUNT_OWNER or row["cls"] == "A":
            continue
        if not os.path.isfile(os.path.join(ROOT, path)):
            continue
        heading_dated = False
        for i, line in enumerate(_read(path).split("\n"), 1):
            if line.startswith("#"):
                # A dated log entry dates its whole section: STATUS is written that way.
                heading_dated = bool(DATE.search(line))
            if DATE.search(line) or heading_dated:
                continue
            for pat in COUNT_PATTERNS:
                m = pat.search(line)
                if m:
                    bad.append((path, i, m.group(0)))
                    break
    return bad


def undated_snapshots():
    """Class-S files with no date in the filename and none in the first 15 lines."""
    bad = []
    for path in by_class("S"):
        if not os.path.isfile(os.path.join(ROOT, path)):
            continue
        if DATE.search(os.path.basename(path)) or DATE.search(head(path)):
            continue
        bad.append(path)
    return bad


def archived_by_location():
    """Markdown under a docs/archive/ SUBdirectory: class A by location, so no registry row is owed.

    docs/archive/*.md is covered a row each (COVERED above). A subdirectory is a block moved whole --
    docs/archive/sprints-1-6/ is twelve files that arrived in one commit -- and a row each would say
    nothing a reader could not see from the path. The banner is still owed: that is the whole point
    of the class, and silent_archives() below holds these files to it.
    """
    out = []
    base = os.path.join(ROOT, "docs", "archive")
    if not os.path.isdir(base):
        return out
    for name in sorted(os.listdir(base)):
        sub = os.path.join(base, name)
        if not os.path.isdir(sub):
            continue
        for dirpath, dirnames, filenames in os.walk(sub):
            dirnames[:] = sorted(dirnames)
            for fn in sorted(filenames):
                if fn.lower().endswith(".md"):
                    rel = os.path.relpath(os.path.join(dirpath, fn), ROOT)
                    out.append(rel.replace(os.sep, "/"))
    return sorted(out)


def silent_archives():
    """Class-A files whose first 15 lines do not say they are archived or superseded."""
    bad = []
    for path in by_class("A") + archived_by_location():
        if not os.path.isfile(os.path.join(ROOT, path)):
            continue
        # Case-insensitive: the house banner is "> **ARCHIVED <date> -- ...**", in capitals, and the
        # old [Aa]rchiv character class did not match it. The banners that existed when this check
        # was written happened to carry "Superseded" as well, so the gap never showed.
        if re.search(r"archiv|supersed|replaced by", head(path), re.I):
            continue
        bad.append(path)
    return bad


def linked_docs():
    """Every markdown file check 6 reads: the repository root's and everything under docs/."""
    out = []
    for name in sorted(os.listdir(ROOT)):
        if name.lower().endswith(".md") and os.path.isfile(os.path.join(ROOT, name)):
            out.append(name)
    docs = os.path.join(ROOT, "docs")
    if os.path.isdir(docs):
        for dirpath, dirnames, filenames in os.walk(docs):
            dirnames[:] = sorted(d for d in dirnames if not d.startswith("."))
            for fn in sorted(filenames):
                if fn.lower().endswith(".md"):
                    rel = os.path.relpath(os.path.join(dirpath, fn), ROOT)
                    out.append(rel.replace(os.sep, "/"))
    return sorted(set(out))


def procedure_docs():
    """The live procedures check 6 also reads (Sprint 14 I2): every `.claude/skills/**/SKILL.md` and every
    `.claude/agents/*.md`. They are not registered documents (the registry covers docs/ and the root), but an
    agent follows their citations as instructions, so a path they cite must exist like any other."""
    out = []
    skills = os.path.join(ROOT, ".claude", "skills")
    if os.path.isdir(skills):
        for dirpath, dirnames, filenames in os.walk(skills):
            dirnames[:] = sorted(dirnames)
            if "SKILL.md" in filenames:
                rel = os.path.relpath(os.path.join(dirpath, "SKILL.md"), ROOT)
                out.append(rel.replace(os.sep, "/"))
    agents = os.path.join(ROOT, ".claude", "agents")
    if os.path.isdir(agents):
        for name in sorted(os.listdir(agents)):
            if name.lower().endswith(".md") and os.path.isfile(os.path.join(agents, name)):
                out.append(".claude/agents/%s" % name)
    return sorted(set(out))


def _cited_paths(line):
    """The docs/ FILES a line claims exist.

    Narrow on purpose, because a check with false positives gets switched off:

    * a locator is not part of the path -- `docs/KNOWN.md:101` and `docs/X.md#anchor` cite a place
      inside a file that does exist;
    * a glob, a brace set or a <placeholder> names a set rather than a file;
    * a token whose last segment has no extension is a directory or the house shorthand for a
      research note by number (`docs/research/19`), and a directory named in a design document is a
      proposal, not a claim. Check 6 is about a file that moved, which is the failure that actually
      happened here.
    """
    for m in BACKTICKED.finditer(line):
        tok = m.group(1).strip()
        if not tok.startswith("docs/"):
            continue
        if line[max(0, m.start() - 2):m.start()] == "~~" and line[m.end():m.end() + 2] == "~~":
            continue                                         # ~~`a/dead/path`~~ is a retraction
        tok = tok.split()[0].split("#")[0]                   # `docs/ROADMAP.md §3`, `...md#anchor`
        tok = LOCATOR.sub("", tok)                           # `...md:101`, `...md:318,355,433-435`
        tok = tok.strip().rstrip(".,;:!?)]>\"'").rstrip("/")
        if not tok or tok == "docs":
            continue
        if any(ch in tok for ch in "*?<>|{}") or "…" in tok or "..." in tok:
            continue
        if "." not in tok.rsplit("/", 1)[-1]:
            continue
        yield tok


def dangling_doc_links():
    """(file, line, target) for every backticked docs/ path that is not in the tree, in the root and docs/
    markdown and in the live procedures (procedure_docs)."""
    bad = []
    for rel in linked_docs() + procedure_docs():
        for i, line in enumerate(_read(rel).split("\n"), 1):
            if FUTURE_MARK in line:
                continue
            for tok in _cited_paths(line):
                if not os.path.exists(os.path.join(ROOT, tok.replace("/", os.sep))):
                    bad.append((rel, i, tok))
    return bad


def block_bytes(relpath, heading):
    """Bytes (LF line ends) of a whole file, or of the "## " block whose heading starts with `heading`.

    The block runs from its heading line to the next level-2 heading or the end of the file. None when
    the file or the heading is missing.
    """
    full = os.path.join(ROOT, relpath)
    if not os.path.isfile(full):
        return None
    with open(full, "rb") as fh:
        data = fh.read().replace(b"\r\n", b"\n")
    if heading is None:
        return len(data)
    lines = data.split(b"\n")
    want = heading.encode("utf-8")
    start = next((i for i, ln in enumerate(lines) if ln.startswith(want)), None)
    if start is None:
        return None
    end = next((i for i in range(start + 1, len(lines)) if lines[i].startswith(b"## ")), len(lines))
    return len(b"\n".join(lines[start:end]))


def over_ceiling():
    """[(path, heading, measured bytes or None, ceiling)] for every R268 ceiling that is broken.

    A missing file is not a problem here (check 1 owns that); a file whose measured heading has gone is,
    because renaming a heading must not quietly switch its ceiling off.
    """
    bad = []
    for path, heading, limit in CEILINGS:
        if not os.path.isfile(os.path.join(ROOT, path)):
            continue
        n = block_bytes(path, heading)
        if n is None or n > limit:
            bad.append((path, heading, n, limit))
    return bad


def describe_ceiling(item):
    path, heading, n, limit = item
    where = "%s %r block" % (path, heading) if heading else "%s (whole file)" % path
    if n is None:
        return "%s: heading not found (ceiling {:,} bytes)".format(limit) % where
    return "%s: {:,} bytes, ceiling {:,}".format(n, limit) % where


# Check 11 (Sprint 14 I4): the read-first budget. The autonomy review of 2026-09-26 (F1) found HANDOFF's
# "read first" list at 975 KB -- a quarter-million tokens a new controller read before acting -- and its minimum
# useful subset at 268 KB. The set is what HANDOFF section 3 tells a new controller to read: HANDOFF itself, the
# root or docs/ .md paths its "Read ..." step names, the plan named on CURRENT_SPRINT's `plans:` line, and
# STATUS's "## Current state" block (the rest of STATUS is a log). LF-counted, like the ceilings. When it fires,
# shrink or archive a member -- never raise the number.
READ_FIRST_BUDGET = 160000
_BACKTICKED = re.compile(r"`([^`\s]+)`")
_PLAN_PATH = re.compile(r"docs/superpowers/plans/[^\s`()]+?\.md")


def _handoff_read_step_paths():
    """The backticked root or docs/ .md paths in HANDOFF section 3's list items that begin "Read"."""
    if not os.path.isfile(os.path.join(ROOT, "docs/HANDOFF.md")):
        return []
    lines = _read("docs/HANDOFF.md").replace("\r\n", "\n").split("\n")
    start = next((i for i, ln in enumerate(lines) if ln.startswith("## 3.")), None)
    if start is None:
        return []
    items, cur = [], None
    for ln in lines[start + 1:]:
        if ln.startswith("## "):
            break
        m = re.match(r"^\s*(?:\d+\.|[-*+])\s+(.*)$", ln)
        if m:
            cur = [m.group(1)]
            items.append(cur)
        elif cur is not None and ln.strip():
            cur.append(ln.strip())
        else:
            cur = None
    out = []
    for item in items:
        text = " ".join(item)
        if not re.match(r"read\b", text, re.I):
            continue
        for tok in _BACKTICKED.findall(text):
            if tok.endswith(".md") and (tok.startswith("docs/") or "/" not in tok):
                out.append(tok)
    return out


def _plans_line_path():
    """The first docs/superpowers/plans/...md path on CURRENT_SPRINT's `plans:` header line, or None."""
    if not os.path.isfile(os.path.join(ROOT, "docs/CURRENT_SPRINT.md")):
        return None
    for ln in _read("docs/CURRENT_SPRINT.md").split("\n"):
        if re.match(r"^plans\s*:", ln):
            m = _PLAN_PATH.search(ln)
            return m.group(0) if m else None
    return None


def read_first_set():
    """The read-first set, in reading order, without repeats (check 11)."""
    names = ["docs/HANDOFF.md"] + _handoff_read_step_paths()
    plan = _plans_line_path()
    if plan:
        names.append(plan)
    names.append("docs/STATUS.md")
    seen = []
    for n in names:
        if n not in seen:
            seen.append(n)
    return seen


def read_first_bytes():
    """[(path, bytes)] for each member that exists; STATUS by its "## Current state" block only."""
    out = []
    for path in read_first_set():
        n = block_bytes(path, "## Current state" if path == "docs/STATUS.md" else None)
        if n is not None:
            out.append((path, n))
    return out


def read_first_over():
    """[members] when the set's sum exceeds READ_FIRST_BUDGET, else [] (check 11)."""
    members = read_first_bytes()
    return [members] if sum(n for _, n in members) > READ_FIRST_BUDGET else []


def describe_read_first(members):
    total = sum(n for _, n in members)
    return "%s = {:,} bytes, budget {:,}".format(total, READ_FIRST_BUDGET) % " + ".join(
        "%s {:,}".format(n) % p for p, n in members)


_TAGS = {}


def remote_tags():
    """(set of tag names on origin, None) -- or (None, why) when origin cannot be asked.

    Asked once per ROOT per process (`git ls-remote --tags origin`, 30 s, no credential prompt).
    """
    if ROOT in _TAGS:
        return _TAGS[ROOT]
    env = dict(os.environ, GIT_TERMINAL_PROMPT="0")
    try:
        p = subprocess.run(["git", "ls-remote", "--tags", "origin"], cwd=ROOT, env=env,
                           capture_output=True, text=True, timeout=30)
    except (OSError, subprocess.SubprocessError) as exc:
        res = (None, "%s: %s" % (type(exc).__name__, exc))
    else:
        if p.returncode != 0:
            err = (p.stderr or "").strip().splitlines()
            res = (None, "git ls-remote exit %d%s" % (p.returncode, (": " + err[0]) if err else ""))
        else:
            tags = set()
            for line in p.stdout.splitlines():
                ref = line.split("\t")[-1].strip()
                if ref.startswith("refs/tags/"):
                    tags.add(ref[len("refs/tags/"):].replace("^{}", ""))
            res = (tags, None)
    _TAGS[ROOT] = res
    return res


def unknown_tags(tags):
    """(path, line, tag) for every live-document "merged to main as vX" whose tag origin lacks."""
    bad = []
    for path in by_class("L"):
        if not os.path.isfile(os.path.join(ROOT, path)):
            continue
        for i, line in enumerate(_read(path).split("\n"), 1):
            for m in MERGED_AS.finditer(STRUCK.sub("", line)):
                tag = "v" + m.group(1)[1:]
                if tag not in tags:
                    bad.append((path, i, tag))
    return bad


def report():
    """One dict for a human or a close-out step."""
    reg = registry()
    listed = [r["path"] for r in reg]
    files = covered_files()
    hi, where = max_ruling()
    tags, why = remote_tags()
    return {
        "rows": len(reg),
        "unregistered": [p for p in files if p not in listed],
        "missing_files": [p for p in listed if not os.path.isfile(os.path.join(ROOT, p))],
        "duplicate_rows": sorted({p for p in listed if listed.count(p) > 1}),
        "max_ruling": hi,
        "max_ruling_in": where,
        "next_free_ruling": next_free_ruling(),
        "count_offenders": count_offenders(),
        "undated_snapshots": undated_snapshots(),
        "silent_archives": silent_archives(),
        "dangling_doc_links": dangling_doc_links(),
        "over_ceiling": over_ceiling(),
        "unknown_tags": unknown_tags(tags) if tags is not None else [],
        "duplicate_rulings": duplicate_rulings(),
        "undefined_rulings": undefined_rulings(),
        "read_first_bytes": read_first_bytes(),
        "read_first_over": read_first_over(),
        "tags_on_origin": len(tags) if tags is not None else None,
        "tag_check_skipped": why,
    }


def main(argv=None):
    r = report()
    print("doc registry: %d rows, %d files covered" % (r["rows"], len(covered_files())))
    print("rulings: highest in use R%d (%s); HANDOFF offers R%s"
          % (r["max_ruling"], r["max_ruling_in"], r["next_free_ruling"]))
    for path, heading, limit in CEILINGS:
        n = block_bytes(path, heading)
        if n is not None and n <= limit:
            print("ceiling: %s" % describe_ceiling((path, heading, n, limit)))
    if not r["read_first_over"]:
        print("read-first: %s" % describe_read_first(r["read_first_bytes"]))
    if r["tag_check_skipped"]:
        # Never pass silently: the run is OK only on what it could check, and says what it could not.
        print("tags: SKIPPED -- origin unreachable (%s); the 'merged to main as vX' check did not run"
              % r["tag_check_skipped"])
    else:
        print("tags: %d on origin; every 'merged to main as vX' checked against them" % r["tags_on_origin"])
    bad = 0
    for key in ("unregistered", "missing_files", "duplicate_rows", "count_offenders",
                "undated_snapshots", "silent_archives", "dangling_doc_links", "unknown_tags"):
        if r[key]:
            bad += len(r[key])
            print("%s:" % key)
            for item in r[key]:
                print("   ", item)
    if r["over_ceiling"]:
        bad += len(r["over_ceiling"])
        print("over_ceiling (R268; archive the oldest blocks, do not raise the number):")
        for item in r["over_ceiling"]:
            print("   ", describe_ceiling(item))
    if r["read_first_over"]:
        bad += 1
        print("read_first_over (check 11; shrink a member or archive its oldest blocks, never raise the number):")
        print("    read-first: %s" % describe_read_first(r["read_first_over"][0]))
    if r["duplicate_rulings"]:
        bad += len(r["duplicate_rulings"])
        print("duplicate_rulings (one number, one ruling; record the second as R<n>b beside it, do not renumber):")
        for name, locs in r["duplicate_rulings"]:
            print("    %s defined %d times: %s" % (name, len(locs), "; ".join("%s:%d" % loc for loc in locs)))
    if r["undefined_rulings"]:
        bad += len(r["undefined_rulings"])
        print("undefined_rulings (cited, never defined; write its text, or 'R<n> -- vacant: <reason>' where "
              "its range is owned):")
        for name, locs in r["undefined_rulings"]:
            more = " (+%d more)" % (len(locs) - 3) if len(locs) > 3 else ""
            print("    %s cited at %s%s" % (name, "; ".join("%s:%d" % loc for loc in locs[:3]), more))
    if r["next_free_ruling"] != r["max_ruling"] + 1:
        bad += 1
        print("ruling counter: HANDOFF says R%s, should be R%d" % (r["next_free_ruling"], r["max_ruling"] + 1))
    print("OK" if not bad else "%d problem(s)" % bad)
    return 0 if not bad else 1


if __name__ == "__main__":
    raise SystemExit(main())
