"""Re-derive the true effective address for every [mmio] override in recomp/socom2.toml.

The existing table was generated by an analysis that truncated many hardware-register
accesses to their `lui` high-half (e.g. I_STAT 0x1000F000 -> 0x10000000), which silently
routes guest MMIO to the wrong register.  For each mmio instruction we backward-reconstruct
the base register value via lui/ori/addiu within its Ghidra function and compute
base + sign_extend(imm16).  Prints a diff; with --write, rewrites the [mmio] table.

Run: python -m tools_py.resolve_mmio [--write]   (from the repository root; reads the r0001
game/overlays/socom2_game.elf, recomp/socom2.toml and recomp/socom2_ghidra.csv; no diff means the
table is right)
"""
import struct
import sys
import csv

ELF = 'game/overlays/socom2_game.elf'
TOML = 'recomp/socom2.toml'
CSV = 'recomp/socom2_ghidra.csv'

f = open(ELF, 'rb').read()
# R+X segment: vaddr 0x100000 -> file off 0x1000, size 0xd5000
SEG_VADDR, SEG_OFF, SEG_SIZE = 0x100000, 0x1000, 0xd5000


def word(vaddr):
    if not (SEG_VADDR <= vaddr < SEG_VADDR + SEG_SIZE):
        return None
    return struct.unpack_from('<I', f, SEG_OFF + (vaddr - SEG_VADDR))[0]


def sx16(v):
    return v - 0x10000 if v & 0x8000 else v


LOAD_STORE = {0x20, 0x21, 0x22, 0x23, 0x24, 0x25, 0x26, 0x27,
              0x28, 0x29, 0x2a, 0x2b, 0x2e, 0x37, 0x3f,
              0x31, 0x39, 0x36, 0x3e, 0x1e, 0x1f, 0x33, 0x3b}


def decode(w):
    op = w >> 26
    rs = (w >> 21) & 31
    rt = (w >> 16) & 31
    imm = w & 0xFFFF
    return op, rs, rt, imm


# function bounds
funcs = []
for row in csv.DictReader(open(CSV)):
    try:
        s = int(row['Start'], 16); e = int(row['End'], 16)
    except (ValueError, KeyError):
        continue
    funcs.append((s, e))
funcs.sort()


def func_start(addr):
    lo, hi, best = 0, len(funcs), None
    for s, e in funcs:
        if s <= addr < e:
            return s
        if s <= addr:
            best = s
    return best if best is not None else (addr & ~0xFFF)


def value_of(reg, idx, fstart, memo, depth=0):
    """value of `reg` just before instruction at vaddr idx; scan backward to fstart."""
    if reg == 0:
        return 0
    if depth > 6:
        return None
    key = (reg, idx)
    if key in memo:
        return memo[key]
    a = idx - 4
    while a >= fstart:
        w = word(a)
        if w is None:
            break
        op, rs, rt, imm = decode(w)
        if op == 0x0F and rt == reg:              # lui
            memo[key] = (imm << 16) & 0xFFFFFFFF
            return memo[key]
        if op == 0x0D and rt == reg:              # ori
            base = value_of(rs, a, fstart, memo, depth + 1)
            memo[key] = None if base is None else (base | imm) & 0xFFFFFFFF
            return memo[key]
        if op == 0x09 and rt == reg:              # addiu
            base = value_of(rs, a, fstart, memo, depth + 1)
            memo[key] = None if base is None else (base + sx16(imm)) & 0xFFFFFFFF
            return memo[key]
        if op == 0x00 and (w & 0x3f) == 0x25 and rt == reg:  # or rd,rs,rt
            rd = (w >> 11) & 31
            if rd == reg:
                b1 = value_of(rs, a, fstart, memo, depth + 1)
                b2 = value_of(rt, a, fstart, memo, depth + 1)
                memo[key] = None if (b1 is None or b2 is None) else (b1 | b2) & 0xFFFFFFFF
                return memo[key]
        # any other write to reg -> unknown
        if writes_reg(w, reg):
            memo[key] = None
            return None
        a -= 4
    memo[key] = None
    return None


def writes_reg(w, reg):
    op = w >> 26
    rs = (w >> 21) & 31
    rt = (w >> 16) & 31
    rd = (w >> 11) & 31
    if op == 0x00:      # special: writes rd (most); jr/jalr special
        fn = w & 0x3f
        if fn in (0x08,):  # jr
            return False
        if fn in (0x18, 0x19, 0x1a, 0x1b):  # mult/div write hi/lo not reg
            return False
        return rd == reg
    if op in (0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f,  # immediate -> rt
              0x18, 0x19, 0x20, 0x21, 0x22, 0x23, 0x24, 0x25, 0x26, 0x27, 0x1e):
        return rt == reg
    if op == 0x1c:  # mmi -> rd usually
        return rd == reg
    return False


# resolve each mmio entry
entries = {}
in_mmio = False
for line in open(TOML, encoding='utf-8'):
    s = line.strip()
    if s == '[mmio]':
        in_mmio = True
        continue
    if in_mmio:
        if s.startswith('[') and s.endswith(']'):
            break
        if s.startswith('"0x'):
            k, v = s.split('=')
            instr = int(k.strip().strip('"'), 16)
            cur = int(v.strip().strip('"'), 16)
            entries[instr] = cur

changed = {}
for instr, cur in sorted(entries.items()):
    w = word(instr)
    if w is None:
        continue
    op, rs, rt, imm = decode(w)
    if op not in LOAD_STORE:
        continue
    fstart = func_start(instr)
    base = value_of(rs, instr, fstart, {})
    if base is None:
        continue
    eff = (base + sx16(imm)) & 0xFFFFFFFF
    if eff != cur:
        changed[instr] = (cur, eff)

print(f"{len(entries)} mmio entries; {len(changed)} would change")
for instr, (cur, eff) in sorted(changed.items()):
    print(f"  0x{instr:06x}: 0x{cur:08x} -> 0x{eff:08x}")

if '--write' in sys.argv and changed:
    lines = open(TOML, encoding='utf-8').read().split('\n')
    out = []
    in_m = False
    for line in lines:
        s = line.strip()
        if s == '[mmio]':
            in_m = True; out.append(line); continue
        if in_m and s.startswith('[') and s.endswith(']'):
            in_m = False
        if in_m and s.startswith('"0x'):
            k, v = s.split('=')
            instr = int(k.strip().strip('"'), 16)
            if instr in changed:
                out.append(f'"0x{instr:x}" = "0x{changed[instr][1]:x}"')
                continue
        out.append(line)
    open(TOML, 'w', encoding='utf-8', newline='\n').write('\n'.join(out))
    print("WROTE", TOML)
