import { defineConfig } from 'vite';
import { readFileSync } from 'fs';
import { resolve } from 'path';
import { dsAlias, fontsAlias, shipFontLicences } from '../shared/vite';

const pkg = JSON.parse(readFileSync(new URL('./package.json', import.meta.url), 'utf-8'));
const stamp = new Date().toISOString().replace('T', ' ').slice(0, 19);

export default defineConfig({
  root: import.meta.dirname,
  define: {
    __APP_VERSION__: JSON.stringify(pkg.version),
    __BUILD_STAMP__: JSON.stringify(stamp),
  },
  // The design system is web/shared/ds, read in place: the pages link /src/ds/index.css and fonts.css names
  // /fonts/*.woff2; both are aliased into web/shared (web/shared/vite.ts), as the viewer's config does.
  resolve: { alias: [dsAlias, fontsAlias] },
  plugins: [shipFontLicences()],
  build: {
    outDir: 'dist',
    emptyOutDir: true,
    // index.html is the scrolling web site (src/home.ts), the default view; classic.html is the 640x480 console menu
    // (src/main.ts), kept whole; story.html is the project's timeline (docs/STORY.md rendered by
    // tools_py/story/site.py), generated by tools/prepare.mjs with its pictures copied under public/story/img/;
    // data.html is the data page; ds/index.html is the design system's gallery.
    rollupOptions: {
      input: {
        main: resolve(import.meta.dirname, 'index.html'),
        classic: resolve(import.meta.dirname, 'classic.html'),
        story: resolve(import.meta.dirname, 'story.html'),
        data: resolve(import.meta.dirname, 'data.html'),
        ds: resolve(import.meta.dirname, 'ds/index.html'),
      },
    },
  },
  // dev: the stats endpoint is firewalled to the production box, so `npm run dev -w landing` reads the live site's
  // proxy. Port 5182, beside the viewer's 5173, clear of 5181 (the owner's viewer dev server) and 5180 (scotho.com's).
  server: { port: 5182, proxy: { '/api/stats': { target: 'https://socomunzipped.com', changeOrigin: true } } },
});
