#!/usr/bin/env python3
"""Sprint 8 Goal 9: a TTF into a C header, so the portable folder stays self-contained.

    python scripts/embed_font.py <in.ttf> <out.h> <symbol>

writes

    static const unsigned char kFont_<symbol>[] = { 0x00, 0x01, ... };
    static const int kFont_<symbol>_len = N;

The generated headers live in third_party/ps2recomp/ps2xLauncher/src/ui/fonts_embedded/ and ARE committed:
the build needs no Python, and a checkout with no network still has its type. Re-run this only when a face
is replaced (the TTFs and their OFL texts are in ps2xLauncher/assets/fonts/).
"""
import os
import sys


def main(argv):
    if len(argv) != 4:
        sys.stderr.write(__doc__)
        return 2
    src, dst, symbol = argv[1], argv[2], argv[3]
    with open(src, "rb") as f:
        data = f.read()
    if data[:4] not in (b"\x00\x01\x00\x00", b"OTTO", b"true", b"ttcf"):
        sys.stderr.write("embed_font: %s does not start with a TrueType/OpenType signature\n" % src)
        return 3
    os.makedirs(os.path.dirname(os.path.abspath(dst)), exist_ok=True)
    out = []
    out.append("#pragma once")
    out.append("// Generated by scripts/embed_font.py from %s -- do not edit." % os.path.basename(src))
    out.append("// SIL Open Font License 1.1; the licence text ships in LICENSES/ (see scripts/make_portable.sh).")
    out.append("static const unsigned char kFont_%s[] = {" % symbol)
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        out.append("    " + ",".join("0x%02x" % b for b in chunk) + ",")
    out.append("};")
    out.append("static const int kFont_%s_len = %d;" % (symbol, len(data)))
    out.append("")
    with open(dst, "w", newline="\n") as f:
        f.write("\n".join(out))
    sys.stderr.write("embed_font: %s -> %s (%d bytes)\n" % (src, dst, len(data)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
