#!/usr/bin/env python3
"""Sprint 10: a PNG into a C header, the way scripts/embed_font.py does a TTF, so the launcher's logo ships
inside the executable and the portable folder stays self-contained.

    python scripts/embed_image.py <in.png> <out.h> <symbol>

writes

    static const unsigned char kImage_<symbol>[] = { 0x89, 0x50, ... };
    static const int kImage_<symbol>_len = N;

The generated header lives in third_party/ps2recomp/ps2xLauncher/src/ui/logo_embedded/ and IS committed:
the build needs no Python. Re-run this only when the artwork is replaced (the PNG is in
ps2xLauncher/assets/logo/; its source is the s2u site's art/logo-unzipped-keyed.webp in the scotho project).
"""
import os
import sys


def main(argv):
    if len(argv) != 4:
        sys.stderr.write(__doc__)
        return 2
    src, dst, symbol = argv[1], argv[2], argv[3]
    with open(src, "rb") as f:
        data = f.read()
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        sys.stderr.write("embed_image: %s does not start with a PNG signature\n" % src)
        return 3
    os.makedirs(os.path.dirname(os.path.abspath(dst)), exist_ok=True)
    out = []
    out.append("#pragma once")
    out.append("// Generated by scripts/embed_image.py from %s -- do not edit." % os.path.basename(src))
    out.append("// The project's own artwork (the SOCOM Unzipped logo, as s2u.scotho.com shows it); nothing from the disc.")
    out.append("static const unsigned char kImage_%s[] = {" % symbol)
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        out.append("    " + ",".join("0x%02x" % b for b in chunk) + ",")
    out.append("};")
    out.append("static const int kImage_%s_len = %d;" % (symbol, len(data)))
    out.append("")
    with open(dst, "w", newline="\n") as f:
        f.write("\n".join(out))
    sys.stderr.write("embed_image: %s -> %s (%d bytes)\n" % (src, dst, len(data)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
