"""The recompiler's naming pipeline, re-derived from the tracked inputs and the recompiler's own rules.
(Sprint 12 research Q12, docs/research/57-recompiler-naming-pipeline.md)

Run from the repo root:  python tools_py/research/symbols/toml_names.py

Read-only. It prints counts, names and addresses only, in labelled blocks the note cites:

  [A] recomp/socom2.toml: every key, its entry count, and whether ps2xRecomp's ConfigManager reads it.
  [B] the name@addr selectors: stubs vs untracked_stubs, duplicate names/addresses, and for each list how
      many addresses are rows of recomp/socom2_ghidra.csv (by the row's name class) and how many are not.
  [C] recomp/extra_functions.txt and recomp/merge_ranges.txt against the csv.
  [D] the name each function gets in recomp/output, by replaying ps2xRecomp's own rules
      (ElfParser::loadDebugFunctions -> ScanJalTargetsFallback, loadGhidraFunctionMap, extractFunctions,
      PS2Recompiler::generateOutput's makeName) over the synthetic ELF, when game/ holds it; the
      FUN_/sub_/named census and the output name at each toml address. Skipped (and said so) without the ELF.
  [E] the proposals files (game/demo_symbol_renames.csv, game/demo_symbol_renames_7b.csv) against the toml.
  [F] rename hazards: which candidate names would change what the recompiler DOES, not only what it
      calls a function (stub-by-name, entry_ prefix, correctness-critical prefixes, authoritative ranges).
  [G] name lengths against PS2Recompiler::clampFilenameLength(…, ".cpp", 100), and the Windows path lengths.
  [H] what-if: the replay re-run with Goal 1's and Goal 6's names written into the csv's Name column --
      files renamed, extents shortened, functions dropped, functions newly stubbed by name.
  [I] tracked files that cite a generated name (<name>_0x<hex>) a rename would change.
  [J] setD3_CHCR vs setD4_CHCR: which DMA channel register (a public PS2 hardware address) each retail and
      demo body stores to.

The ELF, the csv and the proposals are read locally; nothing of the game is printed except addresses,
names and counts (research/44's rule). Python 3.11+ (tomllib).
"""
import bisect
import collections
import csv
import os
import re
import struct
import sys
import tomllib

sys.path.insert(0, os.getcwd())  # run from the repo root

TOML = "recomp/socom2.toml"
CSV = "recomp/socom2_ghidra.csv"
EXTRA = "recomp/extra_functions.txt"
MERGE = "recomp/merge_ranges.txt"
CALL_LIST = "third_party/ps2recomp/ps2xRuntime/include/ps2_call_list.h"
ELF_CANDIDATES = ("game/overlays/socom2_game.elf", "game/disc/socom2_game.elf")
RENAMES = "game/demo_symbol_renames.csv"
RENAMES_7B = "game/demo_symbol_renames_7b.csv"

# ps2xRecomp/src/lib/config_manager.cpp: the keys ConfigManager::loadConfig reads.
READ_KEYS = {
    "general.input", "general.ghidra_output", "general.output", "general.single_file_output",
    "general.low_memory_mode", "general.output_worker_threads", "general.patch_syscalls",
    "general.patch_cop0", "general.patch_cache", "general.stubs", "general.skip",
    "patches.instructions", "mmio", "jump_tables.table",
}
# ps2xRecomp/src/lib/elf_parser.cpp:28 IsAutoGeneratedName
AUTO_PREFIXES = ("sub_", "FUN_", "LAB_", "DAT_")
# ps2xRecomp/src/lib/ps2_recompiler.cpp:2039 IsCorrectnessCriticalFunctionName
CRITICAL_PREFIXES = ("__ct__", "__sinit_", "_GLOBAL__sub_I_", "GLOBAL__sub_I_",
                     "__static_initialization_and_destruction_0", "__do_global_ctors")


def is_auto(name):
    return name.startswith(AUTO_PREFIXES)


def name_class(name):
    for p in ("FUN_", "sub_", "thunk_FUN_", "caseD_", "LAB_", "switchD"):
        if name.startswith(p):
            return p.rstrip("_")
    return "entry" if name == "entry" else "named"


def selectors(values):
    out = []
    for v in values:
        name, _, addr = v.rpartition("@")
        out.append((name.strip(), int(addr, 16)) if name else (v.strip(), None))
    return out


def load_call_list():
    text = open(CALL_LIST).read()
    sys_part, stub_part = text.split("#define PS2_STUB_LIST", 1)
    grab = lambda s: set(re.findall(r"X\(\s*([A-Za-z_][A-Za-z0-9_]*)\s*\)", s))
    return grab(sys_part), grab(stub_part)


def resolves(name, entries):
    """ps2_runtime_calls.h resolveNameWithOptionalLeadingUnderscoreAlias."""
    if not name:
        return False
    if name in entries:
        return True
    if name.startswith("_"):
        return name[1:] in entries
    return ("_" + name) in entries


def sanitize(name):
    """PS2Recompiler::sanitizeFunctionName (ps2_recompiler.cpp:2190 over :49)."""
    s = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if s and not (s[0].isalpha() or s[0] == "_"):
        s = "_" + s
    return s  # keyword / reserved / main prefixes are counted separately in [F]


def read_csv():
    rows = []
    for r in csv.DictReader(open(CSV)):
        rows.append((r["Name"], int(r["Start"], 16), int(r["End"], 16)))
    return rows


# ---------------------------------------------------------------- [D] the recompiler's rules, replayed
def elf_sections(path):
    b = open(path, "rb").read()
    phoff, = struct.unpack_from("<I", b, 28)
    phnum, = struct.unpack_from("<H", b, 44)
    shnum, = struct.unpack_from("<H", b, 48)
    entry, = struct.unpack_from("<I", b, 24)
    secs = []  # AppendLoadSegmentsAsSections: file-backed part of each PT_LOAD; code iff PF_X
    for i in range(phnum):
        t, off, va, _pa, fs, ms, fl, _al = struct.unpack_from("<8I", b, phoff + 32 * i)
        if t == 1 and fs:
            secs.append((va, fs, bool(fl & 1), off))
    secs.sort()
    return b, secs, entry, shnum


def replay(elf_path, rows):
    b, secs, entry, shnum = elf_sections(elf_path)
    code = [(va, va + fs, off) for va, fs, x, off in secs if x]

    def code_sec(a):
        for lo, hi, _o in code:
            if lo <= a < hi:
                return lo, hi
        return None

    def clamp(sec, start, end):
        hi = sec[1]
        if end == 0 or end > hi:
            end = hi
        if end <= start:
            end = start + 4 if start + 4 <= hi else hi
        return end

    # ScanJalTargetsFallback (no DWARF, no section headers in the synthetic ELF)
    starts = set()
    if code_sec(entry):
        starts.add(entry)
    for lo, hi, off in code:
        for o in range(0, hi - lo - 3, 4):
            w, = struct.unpack_from("<I", b, off + o)
            if w >> 26 == 3:
                tgt = ((lo + o + 4) & 0xF0000000) | ((w & 0x03FFFFFF) << 2)
                if code_sec(tgt):
                    starts.add(tgt)
    ss = sorted(starts)
    extras = []
    for i, s in enumerate(ss):
        sec = code_sec(s)
        end = sec[1]
        if i + 1 < len(ss) and s < ss[i + 1] < sec[1]:
            end = ss[i + 1]
        extras.append(("sub_%08X" % s, s, end if end > s else s + 4))
    jal_end = {s: e for _n, s, e in extras}

    # loadGhidraFunctionMap
    map_starts = set()
    for name, s, e in rows:
        sec = code_sec(s)
        if not sec:
            continue
        e = clamp(sec, s, e)
        if e <= s:
            continue
        extras.append((name, s, e))
        map_starts.add(s)
    extras = [f for f in extras if not (is_auto(f[0]) and f[1] not in map_starts)]
    extras.sort(key=lambda f: (f[1], is_auto(f[0]), -f[2], f[0]))
    uniq, seen = [], set()
    for f in extras:
        if f[1] not in seen:
            seen.add(f[1])
            uniq.append(f)

    # extractFunctions (no ELF symbols: only the map/fallback extras)
    auth = {}
    for name, s, e in uniq:
        if s and e > s and name and not is_auto(name) and code_sec(s):
            auth[s] = max(auth.get(s, 0), clamp(code_sec(s), s, e))
    ranges = sorted(auth.items())
    rstarts = [r[0] for r in ranges]

    def inside_auth(s):
        i = bisect.bisect_right(rstarts, s)
        if i == 0:
            return False
        lo, hi = ranges[i - 1]
        return lo < s < hi

    funcs, dropped = [], []
    for name, s, e in uniq:
        if not code_sec(s):
            continue
        if inside_auth(s) and (s not in auth or is_auto(name)):
            dropped.append((name, s))
            continue
        funcs.append((name, s, auth.get(s, e)))
    funcs.sort(key=lambda f: f[1])
    return funcs, dropped, jal_end, shnum, entry


def word_reader(elf_path):
    b, secs, _entry, _shnum = elf_sections(elf_path)

    def word(a):
        for va, fs, _x, off in secs:
            if va <= a < va + fs:
                return struct.unpack_from("<I", b, off + a - va)[0]
        return None
    return word


def branch_target(pc, w):
    """Static branch/jump target of the R5900 word at pc (calls excluded), else None."""
    op, rs, rt = w >> 26, (w >> 21) & 31, (w >> 16) & 31
    rel = pc + 4 + (((w & 0xFFFF) ^ 0x8000) - 0x8000) * 4
    if op in (4, 5, 6, 7, 0x14, 0x15, 0x16, 0x17):
        return rel
    if op == 1 and rt in (0, 1, 2, 3):
        return rel
    if op in (0x10, 0x11, 0x12) and rs == 8:
        return rel
    if op == 2:
        return ((pc + 4) & 0xF0000000) | ((w & 0x03FFFFFF) << 2)
    return None


def output_name(name, start):
    """PS2Recompiler::generateOutput makeName (ps2_recompiler.cpp:1085), without the entry_ special case."""
    return (sanitize(name) or "func") + "_0x%x" % start


def main() -> None:
    doc = tomllib.load(open(TOML, "rb"))
    print("[A] recomp/socom2.toml keys (entries; read by ps2xRecomp ConfigManager?)")
    for table, body in doc.items():
        for key, val in (body.items() if isinstance(body, dict) else [(None, body)]):
            full = f"{table}.{key}" if key else table
            if table == "mmio":
                print(f"    mmio: {len(body)} entries; read={('mmio' in READ_KEYS)}")
                break
            if table == "jump_tables":
                tables = val
                print(f"    jump_tables.table: {len(tables)} tables, {sum(len(t['entries']) for t in tables)} entries; "
                      f"read={'jump_tables.table' in READ_KEYS}")
                continue
            n = len(val) if isinstance(val, list) else "scalar"
            print(f"    {full}: {n}; read={full in READ_KEYS}")

    stubs = selectors(doc["general"]["stubs"])
    untracked = selectors(doc["general"].get("untracked_stubs", []))
    both = [("stubs",) + s for s in stubs] + [("untracked_stubs",) + s for s in untracked]
    rows = read_csv()
    by_start = {s: (n, e) for n, s, e in rows}
    starts_sorted = sorted(by_start)
    print(f"\n[B] name@addr selectors: stubs {len(stubs)}, untracked_stubs {len(untracked)}, total {len(both)}")
    print(f"    without an @addr: {sum(1 for *_x, a in both if a is None)}")
    addrs = collections.Counter(a for *_x, a in both)
    names = collections.Counter(n for _l, n, _a in both)
    print(f"    distinct addresses {len(addrs)}; addresses named twice {[(hex(a), c) for a, c in addrs.items() if c > 1]}")
    print(f"    names at more than one address: {sorted((n, c) for n, c in names.items() if c > 1)}")
    rstarts = sorted(by_start)

    def containing(a):
        i = bisect.bisect_right(rstarts, a) - 1
        if i >= 0 and rstarts[i] < a < by_start[rstarts[i]][1]:
            return rstarts[i]
        return None

    for label, sel in (("stubs", stubs), ("untracked_stubs", untracked), ("all", stubs + untracked)):
        cls = collections.Counter(name_class(by_start[a][0]) for _n, a in sel if a in by_start)
        not_rows = [(n, a) for n, a in sel if a not in by_start]
        agree = sum(1 for n, a in sel if a in by_start and by_start[a][0] == n)
        mid = sum(1 for _n, a in not_rows if containing(a) is not None)
        print(f"    {label}: {len(sel)}; csv rows {len(sel) - len(not_rows)} {dict(cls)}; "
              f"csv name already equal {agree}; NOT csv rows {len(not_rows)} "
              f"(inside a csv row's range {mid}, outside every row {len(not_rows) - mid})")
    not_rows = [(l, n, a) for l, n, a in both if a not in by_start]
    if not_rows:
        print("    not csv rows:", [(l, n, hex(a)) for l, n, a in not_rows])

    print("\n[C] recomp/extra_functions.txt / merge_ranges.txt")
    ex = [int(l.split("#")[0].strip(), 16) for l in open(EXTRA) if l.split("#")[0].strip()]
    print(f"    extra_functions.txt: {len(ex)} addresses ({len(set(ex))} distinct); csv rows {sum(a in by_start for a in ex)}; "
          f"their csv names {dict(collections.Counter(name_class(by_start[a][0]) for a in ex if a in by_start))}")
    mr = [l.split("#")[0].split() for l in open(MERGE) if l.split("#")[0].strip()]
    print(f"    merge_ranges.txt: {len(mr)} range(s)")
    print(f"    csv rows {len(rows)}: {dict(collections.Counter(name_class(n) for n, _s, _e in rows))}; "
          f"starts {hex(min(by_start))}..{hex(max(by_start))}")
    dup = collections.Counter(n for n, _s, _e in rows if not n.startswith("FUN_"))
    dup = {n: c for n, c in dup.items() if c > 1}
    print(f"    csv names at more than one address: {len(dup)} {sorted(dup.items(), key=lambda kv: -kv[1])[:6]}")
    gt = open("recomp/socom2_ghidra.toml").read()
    ghidra_known = {(n, int(a, 16)) for n, a in re.findall(r'"([^"@]+)@0x([0-9A-Fa-f]+)"', gt)}
    real = [(n, s) for n, s, _e in rows if name_class(n) == "named"]
    print(f"    csv real names {len(real)}; of them in recomp/socom2_ghidra.toml's stubs ({len(ghidra_known)}): "
          f"{sum(1 for x in real if x in ghidra_known)}")

    elf = next((p for p in ELF_CANDIDATES if os.path.exists(p)), None)
    out_name = {}
    jal_end = {}
    funcs = []
    print("\n[D] names in recomp/output, replayed from ps2xRecomp's rules")
    if not elf:
        print("    SKIPPED: no synthetic ELF under game/ (", " or ".join(ELF_CANDIDATES), ")")
    else:
        funcs, dropped, jal_end, shnum, entry = replay(elf, rows)
        print(f"    ELF {elf}: section headers {shnum}, entry {hex(entry)}; JAL-scan starts {len(jal_end)}")
        kinds = collections.Counter(name_class(n) for n, _s, _e in funcs)
        print(f"    functions {len(funcs)} -> files {len(funcs)} + register_functions.cpp + 2 headers = {len(funcs) + 3}")
        print(f"    by name class {dict(kinds)}; dropped by extractFunctions {len(dropped)}")
        fun_rows = [s for n, s, _e in rows if n.startswith("FUN_")]
        jal_fun = [s for s in fun_rows if s in jal_end]
        print(f"    csv FUN_ rows {len(fun_rows)}: also a JAL target {len(jal_fun)}; of those the JAL span is longer "
              f"(-> sub_) {sum(1 for s in jal_fun if jal_end[s] > by_start[s][1])}, equal "
              f"{sum(1 for s in jal_fun if jal_end[s] == by_start[s][1])}, shorter "
              f"{sum(1 for s in jal_fun if jal_end[s] < by_start[s][1])}")
        out_name = {s: output_name(n, s) for n, s, _e in funcs}
        fname = {s: n for n, s, _e in funcs}
        for label, sel in (("stubs", stubs), ("untracked_stubs", untracked)):
            c = collections.Counter(name_class(fname[a]) if a in fname else "absent" for _n, a in sel)
            print(f"    {label}: output name class at the toml address {dict(c)}")
        print(f"    toml addresses that are not csv rows and are JAL targets: "
              f"{sum(1 for _l, _n, x in both if x not in by_start and x in jal_end)} of "
              f"{sum(1 for _l, _n, x in both if x not in by_start)}")
        a = 0x0018DBB8
        print(f"    0x0018DBB8: toml {[n for _l, n, x in both if x == a]}, csv {by_start.get(a, ('-',))[0]}, "
              f"csv end {hex(by_start[a][1]) if a in by_start else '-'}, JAL-scan end {hex(jal_end.get(a, 0))}, "
              f"output identifier {out_name.get(a)}")

    print("\n[E] proposals against the toml")
    toml_by_addr = collections.defaultdict(set)
    for _l, n, a in both:
        toml_by_addr[a].add(n)
    for path in (RENAMES, RENAMES_7B):
        if not os.path.exists(path):
            print(f"    {path}: absent")
            continue
        prop = [r for r in csv.DictReader(l for l in open(path) if not l.startswith("#"))]
        on = [r for r in prop if int(r["Address"], 16) in toml_by_addr]
        same = [r for r in on if r["Mangled"] in toml_by_addr[int(r["Address"], 16)]]
        diff = [(r["Address"], sorted(toml_by_addr[int(r["Address"], 16)]), r["Mangled"], r.get("How", r.get("Source")))
                for r in on if r not in same]
        how = collections.Counter(r.get("How", r.get("Source")) for r in on)
        in_stubs = sum(1 for r in prop if int(r["Address"], 16) in {a for _n, a in stubs})
        print(f"    {path}: {len(prop)} rows; on toml addresses {len(on)} {dict(how)} (stubs list {in_stubs}); "
              f"identical {len(same)}; differ {diff}")
        if out_name:
            now_sub = sum(1 for r in prop if name_class(fname.get(int(r["Address"], 16), "")) == "sub")
            print(f"      rows whose output name today is sub_ (their end moves on rename): {now_sub}")
    prop_addrs = set()
    for path in (RENAMES, RENAMES_7B):
        if os.path.exists(path):
            prop_addrs |= {int(r["Address"], 16) for r in csv.DictReader(l for l in open(path) if not l.startswith("#"))}
    toml_only = {a: n for _l, n, a in both if a not in prop_addrs}
    toml_only_rows = {a: n for a, n in toml_only.items() if a in by_start}
    print(f"    toml addresses no proposal names: {len(set(toml_only))}; of them csv rows {len(toml_only_rows)} "
          f"(auto-named {sum(1 for a in toml_only_rows if is_auto(by_start[a][0]))}), not csv rows "
          f"{len(set(toml_only)) - len(toml_only_rows)}")
    print(f"    csv rows whose name the toml would change (csv name != toml name): "
          f"{sum(1 for a in set(a for *_x, a in both) if a in by_start and by_start[a][0] not in toml_by_addr[a])}")

    print("\n[F] names that would change what the recompiler does, not only what it calls a function")
    syscalls, stubnames = load_call_list()
    stub_list_names = {n for n, _a in stubs}
    stub_addrs = {a for _n, a in stubs}
    # PS2Recompiler::isStubFunction (ps2_recompiler.cpp:2023): by start, by a stubs-list name, or by
    # ps2_runtime_calls::isStubName (the PS2_STUB_LIST names, with the leading-underscore alias) -- not syscalls
    by_name = lambda n: n in stub_list_names or resolves(n, stubnames)
    ut_by_name = [(n, a) for n, a in untracked if by_name(n)]
    print(f"    call list: {len(syscalls)} syscalls, {len(stubnames)} stubs")
    print(f"    untracked_stubs names that isStubFunction would match BY NAME (call list or a stubs-list name) "
          f"at an address not in the stubs list: {len([x for x in ut_by_name if x[1] not in stub_addrs])} "
          f"{[(n, hex(a)) for n, a in ut_by_name if a not in stub_addrs][:40]}")
    stubs_not_call = [(n, hex(a)) for n, a in stubs if not (resolves(n, syscalls) or resolves(n, stubnames))]
    print(f"    stubs-list names with no runtime handler (TODO_NAMED): {len(stubs_not_call)} {stubs_not_call[:20]}")
    for path in (RENAMES, RENAMES_7B):
        if not os.path.exists(path):
            continue
        prop = [r for r in csv.DictReader(l for l in open(path) if not l.startswith("#"))]
        try:
            from tools_py.research.symbols.readable_names import readable
        except Exception:  # noqa: BLE001 -- the readable form is optional here
            readable = lambda m: m
        hits = []
        for r in prop:
            a = int(r["Address"], 16)
            for form in {r["Proposed"], readable(r["Mangled"])}:
                if by_name(form) and a not in stub_addrs:
                    hits.append(("stub-by-name", form, r["Address"]))
                if form.startswith(CRITICAL_PREFIXES):
                    hits.append(("correctness-critical", form, r["Address"]))
                if form.startswith("entry_"):
                    hits.append(("entry_", form, r["Address"]))
        print(f"    {path}: proposal names that change behaviour: {len(hits)} "
              f"{collections.Counter(h[0] for h in hits)}")
        for kind in ("stub-by-name", "correctness-critical", "entry_"):
            sel = sorted({(h[2], h[1]) for h in hits if h[0] == kind})
            if sel:
                print(f"      {kind}: {len(sel)} {sel}")
    print("\n[G] lengths (clampFilenameLength(name + '_0x<hex>', '.cpp', 100))")
    all_names = [n for _l, n, _a in both]
    for path in (RENAMES, RENAMES_7B):
        if os.path.exists(path):
            all_names += [r["Proposed"] for r in csv.DictReader(l for l in open(path) if not l.startswith("#"))]
    cut = [n for n in all_names if len(sanitize(n)) + len("_0x") + 6 + len(".cpp") > 100]
    print(f"    names {len(all_names)}; longest {max(map(len, all_names))}; cut in the filename (> 87 chars) {len(cut)}")
    def full_sanitize(n):
        """PS2Recompiler::sanitizeFunctionName: + 'ps2_main' for main, 'ps2_' for a keyword or a reserved
        spelling (two leading underscores, or an underscore and a capital)."""
        t = sanitize(n)
        if t == "main":
            return "ps2_main"
        if re.match(r"^(__|_[A-Z])", t) or t in ("new", "delete", "operator", "this", "class", "int"):
            return "ps2_" + t
        return t
    changed = sorted({n for _l, n, _a in both if full_sanitize(n) != n})
    print(f"    toml names PS2Recompiler::sanitizeFunctionName rewrites (ps2_ prefix): {len(changed)} {changed[:8]}")
    lead = sorted({n for _l, n, _a in both if n.startswith("_")})
    print(f"    toml names with a leading underscore: {len(lead)} {lead[:10]}")
    # Windows paths: the owner's checkout (recomp/socom2_ghidra.toml's output path) and build.sh's runtime tree
    root = "C:\\projects\\socom_pc\\"
    out_dir = root + "recomp\\output\\"
    obj_dir = root + "third_party\\ps2recomp\\build-clang\\ps2xRuntime\\CMakeFiles\\ps2EntryRunner.dir\\"
    print(f"    longest generated file path: {len(out_dir)} + 100 = {len(out_dir) + 100} chars ({out_dir}<100>)")
    print(f"    a non-unity object named after the full source path: {len(obj_dir)} + len('C_\\projects\\socom_pc\\recomp\\output\\') "
          f"{len('C_/projects/socom_pc/recomp/output/')} + 100 + len('.obj') 4 = {len(obj_dir) + len('C_/projects/socom_pc/recomp/output/') + 104}")

    if not elf:
        print("\n[H] SKIPPED: no synthetic ELF")
        return
    print("\n[H] what-if: the same replay with the candidate names written into the csv's Name column")
    try:
        from tools_py.research.symbols.readable_names import readable
    except Exception:  # noqa: BLE001
        readable = lambda m: m
    goal1 = {}
    for path in (RENAMES, RENAMES_7B):
        if os.path.exists(path):
            for r in csv.DictReader(l for l in open(path) if not l.startswith("#")):
                goal1[int(r["Address"], 16)] = readable(r["Mangled"])
    goal6 = {a: n for a, n in toml_only_rows.items() if is_auto(by_start[a][0])}
    base = {s: (n, e) for n, s, e in funcs}
    word = word_reader(elf)

    def stubbed(name, start):
        return start in stub_addrs or by_name(name)

    for label, ren in (("Goal 1 (proposals, readable form)", goal1), ("Goal 6 (toml-only names on auto rows)", goal6),
                       ("Goal 1 + Goal 6", {**goal6, **goal1})):
        new_rows = [(ren.get(s, n), s, e) for n, s, e in rows]
        nf, _nd, _j, _sh, _en = replay(elf, new_rows)
        after = {s: (n, e) for n, s, e in nf}
        gone = sorted(set(base) - set(after))
        added = sorted(set(after) - set(base))
        renamed = [s for s in after if s in base and output_name(*[after[s][0], s]) != output_name(base[s][0], s)]
        shrunk = [s for s in after if s in base and after[s][1] < base[s][1]]
        grown = [s for s in after if s in base and after[s][1] > base[s][1]]
        new_stub = [(hex(s), after[s][0]) for s in after if s in base
                    and stubbed(after[s][0], s) and not stubbed(base[s][0], s)]
        crit = [(hex(s), after[s][0]) for s in after if after[s][0].startswith(CRITICAL_PREFIXES)]
        escapes = 0
        for s in shrunk:
            new_end, old_end = after[s][1], base[s][1]
            for pc in range(s, new_end, 4):
                w = word(pc)
                t = branch_target(pc, w) if w is not None else None
                if t is not None and new_end <= t < old_end:
                    escapes += 1
                    break
        print(f"    {label}: {len(ren)} names; output files renamed {len(renamed)}; functions dropped {len(gone)} "
              f"{[(hex(a), base[a][0]) for a in gone]}; added {len(added)}")
        print(f"      ends shortened {len(shrunk)} (of them with a branch from inside into the cut tail: {escapes}); "
              f"ends lengthened {len(grown)}")
        print(f"      newly stubbed by name {len(new_stub)} {new_stub}; correctness-critical names {len(crit)}")
        if label.startswith("Goal 6"):
            bad = [n for n in goal6.values() if n.startswith("_") or n[0].isdigit()]
            print(f"      toml-only names 1.2 rule 3 refuses (leading underscore): {len(bad)}; "
                  f"names at more than one toml address among them "
                  f"{sum(1 for n in set(goal6.values()) if names[n] > 1)}")

    print("\n[I] tracked files that cite a generated name (<name>_0x<hex>) the renames would change")
    import subprocess
    files = subprocess.run(["git", "ls-files"], capture_output=True, text=True).stdout.split()
    cites = collections.defaultdict(set)
    for f in files:
        if f.endswith((".csv", ".toml", ".bin", ".png", ".jpg", ".zip")) or "sce_symbol_database_data" in f:
            continue
        try:
            text = open(f, errors="ignore").read()
        except OSError:
            continue
        for m in re.finditer(r"\b([A-Za-z_][A-Za-z0-9_]*?)_0x([0-9a-f]{5,7})\b", text):
            if not m.group(1).startswith(("test_", "Clamp", "ReallyLong")):
                cites[(m.group(1), int(m.group(2), 16))].add(f)
    print(f"    citations {len(cites)} in {len({f for v in cites.values() for f in v})} files: "
          f"{sorted({f for v in cites.values() for f in v})}")
    for label, addrs in (("Goal 1", set(goal1)), ("Goal 6", set(goal6) | ({0x180008} if 0x180008 in toml_by_addr else set()))):
        hit = sorted((n, hex(a), sorted(v)) for (n, a), v in cites.items() if a in addrs)
        print(f"    renamed by {label}: {len(hit)} {hit}")

    print("\n[J] setD3_CHCR vs setD4_CHCR: the DMA channel register each body stores to (D3_CHCR 0x1000b000, D4_CHCR 0x1000b400)")
    demo = "game/demo_scus_972_05/SCUS_972.05"
    if not os.path.exists(demo):
        print(f"    SKIPPED: no {demo}")
        return
    from tools_py.elf_symbols import read_elf
    dword = word_reader(demo)

    def chcr(word, start):
        regs, hits = {}, set()
        for i in range(25):
            w = word(start + 4 * i)
            op, rs, rt, imm = w >> 26, (w >> 21) & 31, (w >> 16) & 31, w & 0xFFFF
            if op == 0x0F:
                regs[rt] = imm << 16
            elif op == 0x0D and rs in regs:
                regs[rt] = regs[rs] | imm
            elif op == 0x2B and rs in regs:
                a = (regs[rs] + ((imm ^ 0x8000) - 0x8000)) & 0xFFFFFFFF
                if a in (0x1000B000, 0x1000B400):
                    hits.add({0x1000B000: "D3_CHCR", 0x1000B400: "D4_CHCR"}[a])
        return sorted(hits)
    for n, a in sorted({(n, a) for _l, n, a in both if "CHCR" in n}, key=lambda x: x[1]):
        print(f"    retail {hex(a)} toml {n}: stores to {chcr(word, a)}")
    for s0, _e, n in read_elf(demo).functions:
        if n in ("setD3_CHCR", "setD4_CHCR"):
            print(f"    demo {hex(s0)} {n}: stores to {chcr(dword, s0)}")


if __name__ == "__main__":
    main()
